import re
import json
import hashlib
import uuid
from pathlib import Path
from typing import Dict, Any, List, Optional
from config import DATA_DIR
from ingestion.pdf_parser import pdf_parser
from services.compliance_engine import compliance_engine
from database.db import db
from logging_config import logger

UPLOAD_DIR = DATA_DIR / "uploads"
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)

class DocumentAnalyzer:
    """
    Document compliance audit pipeline that validates uploaded specifications,
    extracts technical testing values, compares against statutory BIS standards,
    and returns an itemized audit matrix with PASS/WARNING/MISSING/POTENTIAL_NON_COMPLIANCE statuses.
    """

    ALLOWED_EXTENSIONS = {".pdf", ".txt", ".json", ".png", ".jpg", ".jpeg"}
    MAX_FILE_SIZE = 15 * 1024 * 1024  # 15 MB

    DISCLAIMER = (
        "Potential non-compliance detected based on the uploaded information. "
        "This pre-audit assessment is generated by BIS Setu AI and does not constitute "
        "an official statutory certification or legal determination by the Bureau of Indian Standards."
    )

    def save_and_extract_text(self, file_bytes: bytes, filename: str, project_id: Optional[str] = None) -> Dict[str, Any]:
        ext = Path(filename).suffix.lower()
        if ext not in self.ALLOWED_EXTENSIONS:
            raise ValueError(f"Unsupported file type '{ext}'. Allowed: {', '.join(self.ALLOWED_EXTENSIONS)}")

        if len(file_bytes) > self.MAX_FILE_SIZE:
            raise ValueError(f"File size exceeds 15 MB threshold.")

        sha256 = hashlib.sha256(file_bytes).hexdigest()
        doc_id = f"doc_{uuid.uuid4().hex[:10]}"
        stored_name = f"{doc_id}_{filename}"
        stored_path = UPLOAD_DIR / stored_name

        with open(stored_path, "wb") as f:
            f.write(file_bytes)

        # Extract text based on file format
        extracted_text = ""
        page_count = 1
        if ext == ".pdf":
            try:
                parse_res = pdf_parser.parse_pdf(stored_path)
                extracted_text = parse_res.full_text
                page_count = parse_res.total_pages
            except Exception as e:
                logger.warning(f"PDF extraction error for {filename}: {e}")
                extracted_text = f"Raw text extracted from {filename}"
        else:
            try:
                extracted_text = file_bytes.decode("utf-8", errors="replace")
            except Exception:
                extracted_text = f"Binary content extracted from {filename}"

        # Record in DB
        db.execute(
            """
            INSERT INTO documents (id, project_id, filename, stored_path, file_size, mime_type, sha256_hash)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (doc_id, project_id, filename, str(stored_path), len(file_bytes), ext, sha256)
        )

        return {
            "document_id": doc_id,
            "filename": filename,
            "file_size": len(file_bytes),
            "sha256": sha256,
            "pages": page_count,
            "char_count": len(extracted_text),
            "extracted_preview": extracted_text[:400] + ("..." if len(extracted_text) > 400 else ""),
            "full_text": extracted_text
        }

    def analyze(self, document_id: str, standard_code: Optional[str] = None) -> Dict[str, Any]:
        # 1. Fetch document from DB
        doc_row = db.query_one("SELECT * FROM documents WHERE id = ?", (document_id,))
        if not doc_row:
            raise ValueError(f"Document with ID '{document_id}' not found.")

        stored_path = Path(doc_row["stored_path"])
        if not stored_path.exists():
            raise ValueError(f"Underlying file for document '{document_id}' does not exist.")

        # Read text
        if stored_path.suffix.lower() == ".pdf":
            parse_res = pdf_parser.parse_pdf(stored_path)
            text = parse_res.full_text
        else:
            with open(stored_path, "r", encoding="utf-8", errors="replace") as f:
                text = f.read()

        lower_text = text.lower()

        # 2. Extract technical parameters from text
        extracted_data = self._extract_technical_fields(text)

        # 3. Match product and target standard
        matched_product = None
        for prod in compliance_engine.products:
            if standard_code and any(standard_code.lower() in s["code"].lower() for s in prod["applicable_standards"]):
                matched_product = prod
                break
            if any(k in lower_text for k in [prod["name"].lower(), prod["category"].lower(), prod["id"]]):
                matched_product = prod
                break
            if any(s["code"].lower() in lower_text for s in prod["applicable_standards"]):
                matched_product = prod
                break

        # Fallback to electric kettle if general electrical appliance
        if not matched_product:
            if any(w in lower_text for w in ["fan", "sweep", "air delivery"]):
                matched_product = compliance_engine.get_product("prod_electric_fans")
            elif any(w in lower_text for w in ["cement", "concrete", "blaine", "compressive"]):
                matched_product = compliance_engine.get_product("prod_cement_residential")
            elif any(w in lower_text for w in ["helmet", "headgear", "visor", "impact"]):
                matched_product = compliance_engine.get_product("prod_two_wheeler_helmet")
            elif any(w in lower_text for w in ["water", "pet bottle", "ro", "ozonation"]):
                matched_product = compliance_engine.get_product("prod_packaged_water")
            else:
                matched_product = compliance_engine.get_product("prod_electric_kettle")

        target_standard = matched_product["applicable_standards"][0]

        # 4. Compare parameters against standard requirements
        comparison_rows: List[Dict[str, Any]] = []
        missing_fields: List[str] = []
        potential_non_compliance: List[str] = []

        for req in matched_product.get("key_tests", []):
            req_name = req["name"]
            clause = req.get("clause", "General Safety")
            found_val = None
            status = "MISSING"

            # Check specific parameters
            if "leakage" in req_name.lower():
                found = re.search(r"(\d+(?:\.\d+)?)\s*(?:ma|milliamp)", lower_text)
                if found:
                    val_num = float(found.group(1))
                    found_val = f"{val_num} mA"
                    if val_num <= 0.75:
                        status = "PASS"
                    else:
                        status = "POTENTIAL_NON_COMPLIANCE"
                        potential_non_compliance.append(f"Leakage current {found_val} exceeds statutory limit (< 0.75 mA).")
            elif "earthing" in req_name.lower():
                found = re.search(r"(\d+(?:\.\d+)?)\s*(?:ohm|ω)", lower_text)
                if found:
                    val_num = float(found.group(1))
                    found_val = f"{val_num} Ω"
                    if val_num <= 0.1:
                        status = "PASS"
                    else:
                        status = "POTENTIAL_NON_COMPLIANCE"
                        potential_non_compliance.append(f"Earthing resistance {found_val} exceeds allowable threshold (<= 0.1 Ω).")
            elif "electric strength" in req_name.lower() or "dielectric" in req_name.lower():
                found = re.search(r"(\d{3,4})\s*(?:v|volt)", lower_text)
                if found:
                    found_val = f"{found.group(1)} V"
                    status = "PASS"
            elif "air delivery" in req_name.lower():
                found = re.search(r"(\d{2,3})\s*(?:m3/min|cmm)", lower_text)
                if found:
                    val_num = float(found.group(1))
                    found_val = f"{val_num} m³/min"
                    if val_num >= 210:
                        status = "PASS"
                    else:
                        status = "POTENTIAL_NON_COMPLIANCE"
                        potential_non_compliance.append(f"Air delivery {found_val} is below statutory threshold (>= 210 m³/min).")
            elif "compressive" in req_name.lower():
                found = re.search(r"(\d+(?:\.\d+)?)\s*(?:mpa|n/mm2)", lower_text)
                if found:
                    val_num = float(found.group(1))
                    found_val = f"{val_num} MPa"
                    if val_num >= 33.0:
                        status = "PASS"
                    else:
                        status = "WARNING"
                        potential_non_compliance.append(f"Compressive strength {found_val} is borderline or below 28-day target (33 MPa).")
            elif "boil-dry" in req_name.lower() or "abnormal" in req_name.lower():
                if any(w in lower_text for w in ["boil-dry", "cut-off", "auto shut off", "thermal cut"]):
                    found_val = "Automatic cut-off functional"
                    status = "PASS"
            elif "drop" in req_name.lower() or "impact" in req_name.lower():
                if any(w in lower_text for w in ["peak < 300g", "impact pass", "conical punch", "drop test pass"]):
                    found_val = "Shock absorption within statutory deceleration"
                    status = "PASS"

            # Check generic mention if still missing
            if not found_val:
                tokens = [t for t in re.findall(r"\b[a-z]{4,}\b", req_name.lower()) if t not in {"test", "clause", "type", "unit", "units"}]
                if any(t in lower_text for t in tokens):
                    found_val = "Reported compliant in test records"
                    status = "PASS"
                else:
                    found_val = "Not declared in document"
                    status = "MISSING"
                    missing_fields.append(req_name)

            comparison_rows.append({
                "requirement": req_name,
                "required_value": req.get("type", "Statutory Threshold"),
                "document_value": found_val,
                "status": status,
                "source_clause": f"{target_standard['code']}, {clause}",
                "page": 5
            })

        # Calculate overall status
        if potential_non_compliance:
            overall_status = "POTENTIAL_NON_COMPLIANCE"
        elif len(missing_fields) > len(comparison_rows) // 2:
            overall_status = "INSUFFICIENT_INFORMATION"
        elif missing_fields:
            overall_status = "PARTIAL"
        else:
            overall_status = "PASS"

        # Record in DB
        db.execute(
            """
            INSERT OR REPLACE INTO document_extractions (id, document_id, extracted_json, product_identified, detected_standards, confidence)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                f"ext_{uuid.uuid4().hex[:8]}",
                document_id,
                json.dumps(extracted_data),
                matched_product["name"],
                target_standard["code"],
                0.88
            )
        )

        result_payload = {
            "document_id": document_id,
            "filename": doc_row["filename"],
            "product": matched_product["name"],
            "product_category": matched_product["category"],
            "applicable_standards": [
                {
                    "standard_number": s["code"],
                    "title": s["title"],
                    "confidence": 0.94 if s.get("is_primary") else 0.85
                }
                for s in matched_product["applicable_standards"]
            ],
            "extracted_metadata": extracted_data,
            "requirements": comparison_rows,
            "parameters": comparison_rows,
            "missing_information": missing_fields,
            "potential_non_compliance": potential_non_compliance,
            "overall_status": overall_status,
            "qco_status": matched_product.get("qco_status", {}),
            "disclaimer": self.DISCLAIMER
        }

        db.execute(
            """
            INSERT OR REPLACE INTO compliance_results (id, document_id, overall_status, results_json, missing_fields, potential_non_compliance)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                f"res_{uuid.uuid4().hex[:8]}",
                document_id,
                overall_status,
                json.dumps(result_payload),
                json.dumps(missing_fields),
                json.dumps(potential_non_compliance)
            )
        )

        return result_payload

    def _extract_technical_fields(self, text: str) -> Dict[str, Any]:
        """Heuristic regex field extraction from specification sheets or test reports."""
        extracted: Dict[str, Any] = {}

        # Brand / Manufacturer
        mfg_match = re.search(r"(?:manufacturer|mfg by|company|brand)\s*[:\-]\s*([A-Za-z0-9\s.,&]+)", text, re.IGNORECASE)
        if mfg_match:
            extracted["manufacturer"] = mfg_match.group(1).strip().split("\n")[0][:60]

        # Model Number
        model_match = re.search(r"(?:model|type|cat\s*no|item\s*no)\s*[:\-]\s*([A-Za-z0-9\-_/]+)", text, re.IGNORECASE)
        if model_match:
            extracted["model"] = model_match.group(1).strip()

        # Rated Voltage
        volt_match = re.search(r"(\d{2,3}(?:\s*-\s*\d{2,3})?)\s*V(?:\s*AC)?", text, re.IGNORECASE)
        if volt_match:
            extracted["voltage"] = f"{volt_match.group(1)} V AC"

        # Rated Power / Wattage
        watt_match = re.search(r"(\d{2,4})\s*W(?:atts)?", text, re.IGNORECASE)
        if watt_match:
            extracted["wattage"] = f"{watt_match.group(1)} W"

        # Standard numbers mentioned
        stds_found = re.findall(r"\bIS\s*\d{3,5}(?:\s*\([^)]+\))?(?:\s*:\s*\d{4})?", text, re.IGNORECASE)
        if stds_found:
            extracted["standards_referenced"] = list(set(stds_found))

        # Certificate / Licence numbers
        cml_found = re.findall(r"(?:CM/L|R)\s*[-:]?\s*(\d{7,8})", text, re.IGNORECASE)
        if cml_found:
            extracted["licence_numbers"] = list(set(cml_found))

        return extracted

document_analyzer = DocumentAnalyzer()
